package edu.estu.entities.concretes;

public enum Unit {
    BOTTLE, CAN, CUP, DASH, DROP//, GALLON, GRAM, KILOGRAM, LITER, MILLILITER, OUNCE, PINT, POUND, QUART, TABLESPOON, TEASPOON, COUNT, PIECE, SLICE, HANDFUL, BUNCH, PINCH, PACKAGE, BAG, BOX, DOZEN, HEAD, SPRIG, STALK, LEAF, WHOLE, HALF, QUARTER
}